export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';

export const LOAD_ANSWER_REQUEST = 'LOAD_ANSWER_REQUEST';
export const LOAD_ANSWER_SUCCESS = 'LOAD_ANSWER_SUCCESS';

export const DELETE_ANSWER_REQUEST = 'DELETE_ANSWER_REQUEST';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';

export const EDIT_ANSWER_REQUEST = 'EDIT_ANSWER_REQUEST';
export const EDIT_ANSWER_SUCCESS = 'EDIT_ANSWER_SUCCESS';

export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';

export const ANSWER_INTERN_BY_MENTOR_REQUEST = 'ANSWER_INTERN_BY_MENTOR_REQUEST';
export const ANSWER_INTERN_BY_MENTOR_SUCCESS = 'ANSWER_INTERN_BY_MENTOR_SUCCESS';

export const PUT_MARK_REQUEST = 'PUT_MARK_REQUEST';
export const PUT_MARK_SUCCESS = 'PUT_MARK_SUCCESS';

export const ASSIGN_INTERN_TO_ASSIGNMENT_REQUEST = 'ASSIGN_INTERN_TO_ASSIGNMENT_REQUEST';
export const ASSIGN_INTERN_TO_ASSIGNMENT_SUCCESS = 'ASSIGN_INTERN_TO_ASSIGNMENT_SUCCESS';