export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';

export const LOAD_ANSWER_REQUEST = 'LOAD_ANSWER_REQUEST';
export const LOAD_ANSWER_SUCCESS = 'LOAD_ANSWER_SUCCESS';

export const DELETE_ANSWER_REQUEST = 'DELETE_ANSWER_REQUEST';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';

export const EDIT_ANSWER_REQUEST = 'EDIT_ANSWER_REQUEST';
export const EDIT_ANSWER_SUCCESS = 'EDIT_ANSWER_SUCCESS';

export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';