export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';

export const LOAD_ASSIGNMENTS_REQUEST = 'LOAD_ASSIGNMENTS_REQUEST';
export const LOAD_ASSIGNMENTS_SUCCESS = 'LOAD_ASSIGNMENTS_SUCCESS';