export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';

export const LOAD_ASSIGNMENTS_REQUEST = 'LOAD_ASSIGNMENTS_REQUEST';
export const LOAD_ASSIGNMENTS_SUCCESS = 'LOAD_ASSIGNMENTS_SUCCESS';

export const EDIT_ASSIGNMENTS_REQUEST = 'EDIT_ASSIGNMENTS_REQUEST';
export const EDIT_ASSIGNMENTS_SUCCESS = 'EDIT_ASSIGNMENTS_SUCCESS';

export const LOAD_ID_ASSIGNMENT_REQUEST = 'LOAD_ID_ASSIGNMENT_REQUEST';
export const LOAD_ID_ASSIGNMENT_SUCCESS = 'LOAD_ID_ASSIGNMENT_SUCCESS';

export const DELETE_ASSIGNMENT_REQUEST = 'DELETE_ASSIGNMENT_REQUEST';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';

export const LOAD_ANSWERS_ASSIGNMENT_REQUEST = 'LOAD_ANSWERS_ASSIGNMENT_REQUEST';
export const LOAD_ANSWERS_ASSIGNMENT_SUCCESS = 'LOAD_ANSWERS_ASSIGNMENT_SUCCESS';

export const DELETE_ANSWER_MENTOR_REQUEST = 'DELETE_ANSWER_MENTOR_REQUEST';
export const DELETE_ANSWER_MENTOR_SUCCESS = 'DELETE_ANSWER_MENTOR_SUCCESS';