export const LOAD_COMMENT_ANSWER_REQUEST = 'LOAD_COMMENT_ANSWER_REQUEST';
export const LOAD_COMMENT_ANSWER_SUCCESS = 'LOAD_COMMENT_ANSWER_SUCCESS';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';

export const DETELE_COMMENT_REQUEST = 'DETELE_COMMENT_REQUEST';
export const DETELE_COMMENT_SUCCESS = 'DETELE_COMMENT_SUCCESS';