export const LOAD_MENTOR_DETAIL_REQUEST = 'LOAD_MENTOR_DETAIL_REQUEST';
export const LOAD_MENTOR_DETAIL_SUCCESS = 'LOAD_MENTOR_DETAIL_SUCCESS';
export const LOAD_MENTOR_DETAIL_FAILURE = 'LOAD_MENTOR_DETAIL_FAILURE';

export const LOAD_ASSIGNMENT_OF_INTERN_REQUEST = 'LOAD_ASSIGNMENT_OF_INTERN_REQUEST';
export const LOAD_ASSIGNMENT_OF_INTERN_SUCCESS = 'LOAD_ASSIGNMENT_OF_INTERN_SUCCESS';